spring.mvc.view.prefix: /
spring.mvc.view.suffix: .html
application.message: Hello World

# Session timeout in seconds.
server.session.timeout:
  999999999
  
server:
  port: 8004

spring:
  data:
    mongodb:
      uri: mongodb://172.18.4.117:27017/Test
  elastic: 
    host: 172.18.4.117
    port: 9300    
         
logging.config:
     classpath:logback.xml
          
#spring.elastic.port: 172.18.4.117
#spring.elastic.port: 9300   